// Branded icon component for the assets/icons/ library.
//
// Renders via react-native-svg's <SvgXml> from the inline registry
// (components/ui/iconRegistry.ts, generated by scripts/gen-icon-registry.mjs)
// — the same approach as components/ui/Illustrations.tsx, because
// react-native-svg-transformer is intentionally NOT installed (frozen
// lockfile) so .svg files can't be imported as components.
//
// Recolor contract: the source icons use stroke="currentColor"; we swap it
// for the passed color, exactly like Illustrations.StampRing and
// StampArtwork. Defaults to palette.ink.
import React from 'react'
import { SvgXml } from 'react-native-svg'
import { palette } from '../../lib/colors'
import { ICON_REGISTRY, type IconName } from './iconRegistry'

export type { IconName }

export function Icon({
  name,
  color = palette.ink,
  size = 24,
}: {
  name: IconName
  color?: string
  size?: number
}) {
  const raw = ICON_REGISTRY[name]
  if (!raw) return null
  const xml = raw.replace(/currentColor/g, color)
  return <SvgXml xml={xml} width={size} height={size} />
}
